name: Node CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: drewsher/beget-deploy@master
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}